backend:
  name: git-gateway
  repo: free-xueq-jianb/free-xueq-jianb.github.io
  branch: main # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "source/images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "source/_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "封面图片（选填）", name: "cover", widget: "image", required: false}
      - {label: "类别（媒体报道、案件通报、雪饼的朋友心声）", name: "categories", widget: "list"}
      - {label: "标签（中间用英文逗号分隔）", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}